openapi: 3.0.0

info:
  title: Node Api
  description: api for dev.io clone
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: main server

paths:
  /auth/register:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string

      responses:
        '201':
          description: Created
